### ISSUE TITLE
The version of CARLA simulator

### ISSUE THREAD

**Issue by staghavi93** [paulyehtw/Lane-Keeping-Assist-on-CARLA#1]
I tried to download the carla simulator via the link you put in the reading section but I redirected to a blank page. I could run carla and it's client api successfully but I think your code can run on a specified version. Which carla simulator version you are using?

**Comment by ericwang555** [comment]
Hello Paul, could you share your racetrack map to me, thank you.

**Comment by paulyehtw** [comment]
@staghavi93 I think the link I provided was broken, if you register the course I took on Coursera, you should able to download the correct version

**Comment by paulyehtw** [comment]
@ericwang555 I could be downloaded alone with the simulator

**Comment by julingers** [comment]
Hello Paul, the link you provided cannot be run with errors,could you share your racktrack map to me, thank you very much!

**Comment by paulyehtw** [comment]
> Hello Paul, the link you provided cannot be run with errors,could you share your racktrack map to me, thank you very much!

Hi @Julyers 
Sorry for the broken link, I have moved it to dropbox, please check the link below :
https://www.dropbox.com/s/hu06pg118qqbd67/CarlaUE4Ubuntu.tar.gz?dl=0
