### ISSUE TITLE
How to install your live_plotter library? 

### ISSUE THREAD

**Issue by berleyzheng** [paulyehtw/Lane-Keeping-Assist-on-CARLA#2]
get the following error:

➜  Motion-Planning-on-CARLA git:(master) ✗ python3 module_7.py 
Traceback (most recent call last):
  File "module_7.py", line 34, in <module>
    import live_plotter as lv   # Custom live plotting library
ImportError: No module named 'live_plotter'

How to install your custom live plotter? I have installed carla simulator.

**Comment by Zhangzepuno1** [comment]
same problem.

**Comment by muhenan** [comment]
same

**Comment by Zhangzepuno1** [comment]
> same

its a python file, you could search it on github,very easy

**Comment by 18887044028** [comment]
I have installed live-plotter,but still appear the same problem,can you tell me how to deal with it in detail,thanks!

**Comment by 18887044028** [comment]
> > same
> 
> its a python file, you could search it on github,very easy

Can you share with me how to solve that problem？thanks sincerely！

**Comment by muhenan** [comment]
I haven't seen this for a long time, I almost forgot. Sorry, my bro.

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "18887044028"<notifications@github.com&gt;; 
发送时间: 2020年3月22日(星期天) 上午8:35
收件人: "paulyehtw/Lane-Keeping-Assist-on-CARLA"<Lane-Keeping-Assist-on-CARLA@noreply.github.com&gt;; 
抄送: "Allen&amp;#x1F33A;"<1149423577@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [paulyehtw/Lane-Keeping-Assist-on-CARLA] How to install your live_plotter library?  (#2)





   
same
  
its a python file, you could search it on github,very easy
  
Can you share with me how to solve that problem？thanks sincerely！

**Comment by 18887044028** [comment]
> > same
> 
> its a python file, you could search it on github,very easy

I have tried many files on github,but not support,can you give me the link？THANKS!

**Comment by 18887044028** [comment]
> I haven't seen this for a long time, I almost forgot. Sorry, my bro.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "18887044028"<notifications@github.com&gt;; 发送时间: 2020年3月22日(星期天) 上午8:35 收件人: "paulyehtw/Lane-Keeping-Assist-on-CARLA"<Lane-Keeping-Assist-on-CARLA@noreply.github.com&gt;; 抄送: "Allen&amp;#x1F33A;"<1149423577@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [paulyehtw/Lane-Keeping-Assist-on-CARLA] How to install your live_plotter library? (#2) same its a python file, you could search it on github,very easy Can you share with me how to solve that problem？thanks sincerely！ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Could you give me your e-mail address? I have some questions to consult you ! please!

**Comment by varad-more** [comment]
Put "Course1FinalProject" folder inside "PythonClient" folder

Hope this solves your problem. It worked for me.

**Comment by berleyzheng** [comment]
[Lane-Keeping-Assist-on-CARLA.zip](https://github.com/paulyehtw/Lane-Keeping-Assist-on-CARLA/files/4671155/Lane-Keeping-Assist-on-CARLA.zip)

I'm sorry everyone, because I was busy before and didn't pay much attention to this issue. I have solved this problem. The file can be found directly on the Internet, I have compressed and uploaded my version, I hope to help everyone

**Comment by teja2002** [comment]
can anyone help still my problem was not resolved

**Comment by olyii** [comment]
> 

can't download

**Comment by yihsinma** [comment]
how to solve this problem?
(LKA) ma@ma-ROG-Strix:~/Downloads/CarlaSimulator/PythonClient/Lane-Keeping-Assist-on-CARLA$ python3 module_7.py --control-method MPC
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: listening to server localhost:2000
Control method selected : MPC

Carla client connected.
Starting new episode at 'Town01'...
SERVER SIMULATION STEP APPROXIMATION: 0.0716
/home/ma/Downloads/CarlaSimulator/PythonClient/Lane-Keeping-Assist-on-CARLA/live_plotter.py:25: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.fig.tight_layout()
/home/ma/Downloads/CarlaSimulator/PythonClient/Lane-Keeping-Assist-on-CARLA/live_plotter.py:25: UserWarning: tight_layout : falling back to Agg renderer
  self.fig.tight_layout()
Traceback (most recent call last):
  File "module_7.py", line 820, in <module>
    main()
  File "module_7.py", line 809, in main
    exec_waypoint_nav_demo(args)
  File "module_7.py", line 440, in exec_waypoint_nav_demo
    rect=[PLOT_LEFT, PLOT_BOT, PLOT_WIDTH, PLOT_HEIGHT])
  File "/home/ma/Downloads/CarlaSimulator/PythonClient/Lane-Keeping-Assist-on-CARLA/live_plotter.py", line 257, in plot_new_dynamic_2d_figure
    self.plot_figure(fig)
  File "/home/ma/Downloads/CarlaSimulator/PythonClient/Lane-Keeping-Assist-on-CARLA/live_plotter.py", line 230, in plot_figure
    _backend_tk.blit(photo, fca.get_renderer()._renderer, colormode=2)
TypeError: blit() got an unexpected keyword argument 'colormode'
